/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AdminRouteImport } from './routes/_admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminOnboardingRouteImport } from './routes/_admin/onboarding'
import { Route as AdminDashboardRouteImport } from './routes/_admin/dashboard'
import { Route as AdminReconciliationIndexRouteImport } from './routes/_admin/reconciliation/index'
import { Route as AdminMerchantsIndexRouteImport } from './routes/_admin/merchants/index'
import { Route as AdminAuditIndexRouteImport } from './routes/_admin/audit/index'
import { Route as AdminReconciliationBatchIdRouteImport } from './routes/_admin/reconciliation/$batchId'
import { Route as AdminMerchantsMerchantIdRouteImport } from './routes/_admin/merchants/$merchantId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/_admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminOnboardingRoute = AdminOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReconciliationIndexRoute =
  AdminReconciliationIndexRouteImport.update({
    id: '/reconciliation/',
    path: '/reconciliation/',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminMerchantsIndexRoute = AdminMerchantsIndexRouteImport.update({
  id: '/merchants/',
  path: '/merchants/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAuditIndexRoute = AdminAuditIndexRouteImport.update({
  id: '/audit/',
  path: '/audit/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReconciliationBatchIdRoute =
  AdminReconciliationBatchIdRouteImport.update({
    id: '/reconciliation/$batchId',
    path: '/reconciliation/$batchId',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminMerchantsMerchantIdRoute =
  AdminMerchantsMerchantIdRouteImport.update({
    id: '/merchants/$merchantId',
    path: '/merchants/$merchantId',
    getParentRoute: () => AdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof AdminDashboardRoute
  '/onboarding': typeof AdminOnboardingRoute
  '/merchants/$merchantId': typeof AdminMerchantsMerchantIdRoute
  '/reconciliation/$batchId': typeof AdminReconciliationBatchIdRoute
  '/audit/': typeof AdminAuditIndexRoute
  '/merchants/': typeof AdminMerchantsIndexRoute
  '/reconciliation/': typeof AdminReconciliationIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof AdminDashboardRoute
  '/onboarding': typeof AdminOnboardingRoute
  '/merchants/$merchantId': typeof AdminMerchantsMerchantIdRoute
  '/reconciliation/$batchId': typeof AdminReconciliationBatchIdRoute
  '/audit': typeof AdminAuditIndexRoute
  '/merchants': typeof AdminMerchantsIndexRoute
  '/reconciliation': typeof AdminReconciliationIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_admin': typeof AdminRouteWithChildren
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/_admin/dashboard': typeof AdminDashboardRoute
  '/_admin/onboarding': typeof AdminOnboardingRoute
  '/_admin/merchants/$merchantId': typeof AdminMerchantsMerchantIdRoute
  '/_admin/reconciliation/$batchId': typeof AdminReconciliationBatchIdRoute
  '/_admin/audit/': typeof AdminAuditIndexRoute
  '/_admin/merchants/': typeof AdminMerchantsIndexRoute
  '/_admin/reconciliation/': typeof AdminReconciliationIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/login'
    | '/dashboard'
    | '/onboarding'
    | '/merchants/$merchantId'
    | '/reconciliation/$batchId'
    | '/audit/'
    | '/merchants/'
    | '/reconciliation/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/login'
    | '/dashboard'
    | '/onboarding'
    | '/merchants/$merchantId'
    | '/reconciliation/$batchId'
    | '/audit'
    | '/merchants'
    | '/reconciliation'
  id:
    | '__root__'
    | '/'
    | '/_admin'
    | '/about'
    | '/login'
    | '/_admin/dashboard'
    | '/_admin/onboarding'
    | '/_admin/merchants/$merchantId'
    | '/_admin/reconciliation/$batchId'
    | '/_admin/audit/'
    | '/_admin/merchants/'
    | '/_admin/reconciliation/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AboutRoute: typeof AboutRoute
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin': {
      id: '/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin/onboarding': {
      id: '/_admin/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AdminOnboardingRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/dashboard': {
      id: '/_admin/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/reconciliation/': {
      id: '/_admin/reconciliation/'
      path: '/reconciliation'
      fullPath: '/reconciliation/'
      preLoaderRoute: typeof AdminReconciliationIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/merchants/': {
      id: '/_admin/merchants/'
      path: '/merchants'
      fullPath: '/merchants/'
      preLoaderRoute: typeof AdminMerchantsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/audit/': {
      id: '/_admin/audit/'
      path: '/audit'
      fullPath: '/audit/'
      preLoaderRoute: typeof AdminAuditIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/reconciliation/$batchId': {
      id: '/_admin/reconciliation/$batchId'
      path: '/reconciliation/$batchId'
      fullPath: '/reconciliation/$batchId'
      preLoaderRoute: typeof AdminReconciliationBatchIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/merchants/$merchantId': {
      id: '/_admin/merchants/$merchantId'
      path: '/merchants/$merchantId'
      fullPath: '/merchants/$merchantId'
      preLoaderRoute: typeof AdminMerchantsMerchantIdRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminOnboardingRoute: typeof AdminOnboardingRoute
  AdminMerchantsMerchantIdRoute: typeof AdminMerchantsMerchantIdRoute
  AdminReconciliationBatchIdRoute: typeof AdminReconciliationBatchIdRoute
  AdminAuditIndexRoute: typeof AdminAuditIndexRoute
  AdminMerchantsIndexRoute: typeof AdminMerchantsIndexRoute
  AdminReconciliationIndexRoute: typeof AdminReconciliationIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminDashboardRoute: AdminDashboardRoute,
  AdminOnboardingRoute: AdminOnboardingRoute,
  AdminMerchantsMerchantIdRoute: AdminMerchantsMerchantIdRoute,
  AdminReconciliationBatchIdRoute: AdminReconciliationBatchIdRoute,
  AdminAuditIndexRoute: AdminAuditIndexRoute,
  AdminMerchantsIndexRoute: AdminMerchantsIndexRoute,
  AdminReconciliationIndexRoute: AdminReconciliationIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AboutRoute: AboutRoute,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
